//! AES-encrypted pak fixtures: key constants and plaintext constants.
//!
//! # Vendored static fixtures
//!
//! The three `real_v8b_encrypted_*.pak` files in `tests/fixtures/` are
//! VENDORED-STATIC: committed directly to the repo, NOT regenerated by the
//! fixture-gen binary. They are excluded from the CI `rm + regenerate` cycle.
//!
//! **Provenance**: vendored from [`trumank/repak`] (MIT/Apache-2.0) test suite
//! (`repak/tests/packs/pack_v8b_encrypt*.pak`), originally produced by
//! UnrealPak. See `tests/fixtures/PROVENANCE-encrypted.md` for full attribution.
//!
//! [`trumank/repak`]: https://github.com/trumank/repak
//!
//! # Fixture inventory
//!
//! Three fixtures, all v8b, mount `"../mount/point/root/"`:
//! - `real_v8b_encrypted_entries.pak` — per-entry AES-256-ECB, plaintext index
//! - `real_v8b_encrypted_index.pak`   — encrypted index, plaintext entry data
//! - `real_v8b_encrypted_both.pak`    — both index and entry data encrypted
//!
//! **Mount point note**: all three fixtures use [`FIXTURE_ENCRYPTED_MOUNT_POINT`],
//! NOT paksmith's standard `MOUNT_POINT = "../../../"`. Tasks 3–5 that assert
//! the mount point must use [`FIXTURE_ENCRYPTED_MOUNT_POINT`], not `MOUNT_POINT`.
//!
//! All three share the same four entries:
//! `test.txt`, `directory/nested.txt`, `zeros.bin`, `test.png`.
//!
//! # Key
//!
//! [`FIXTURE_AES_KEY`] is the 32-byte AES-256 key for all three fixtures
//! (base64: `lNJbw660IOC+kU7cnVQ1oeqrXyhk4J6UAZrCBbcnp94=`). Tasks 3–5 must
//! supply this key to paksmith's decryption layer.
//!
//! # Plaintext entries
//!
//! | Path                   | Constant                               |
//! |------------------------|----------------------------------------|
//! | `test.txt`             | [`FIXTURE_PLAINTEXT_TEST_TXT`]         |
//! | `directory/nested.txt` | [`FIXTURE_PLAINTEXT_NESTED_TXT`]       |
//! | `zeros.bin`            | [`FIXTURE_ZEROS_BIN_LEN`] zero bytes   |
//! | `test.png`             | [`FIXTURE_TEST_PNG_LEN`] bytes (large) |

/// AES-256 key for the vendored encrypted pak fixtures.
///
/// Decoded from base64 `lNJbw660IOC+kU7cnVQ1oeqrXyhk4J6UAZrCBbcnp94=`.
/// Tasks 3–5 should use this constant rather than hardcoding raw bytes.
pub const FIXTURE_AES_KEY: [u8; 32] = [
    0x94, 0xd2, 0x5b, 0xc3, 0xae, 0xb4, 0x20, 0xe0, 0xbe, 0x91, 0x4e, 0xdc, 0x9d, 0x54, 0x35, 0xa1,
    0xea, 0xab, 0x5f, 0x28, 0x64, 0xe0, 0x9e, 0x94, 0x01, 0x9a, 0xc2, 0x05, 0xb7, 0x27, 0xa7, 0xde,
];

/// Mount point written into all vendored encrypted pak fixtures.
///
/// **Not** the same as `paksmith_fixture_gen::MOUNT_POINT` (`"../../../"`).
/// Tasks 3–5 must use this constant when asserting the mount point of these
/// fixtures, not the workspace-standard one.
pub const FIXTURE_ENCRYPTED_MOUNT_POINT: &str = "../mount/point/root/";

/// Plaintext content of `test.txt` inside all encrypted fixtures.
pub const FIXTURE_PLAINTEXT_TEST_TXT: &[u8] = b"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n";

/// Plaintext content of `directory/nested.txt` inside all encrypted fixtures.
pub const FIXTURE_PLAINTEXT_NESTED_TXT: &[u8] = b"Proin urna leo, placerat non tristique sed, commodo sit amet enim. Nam aliquet metus et turpis semper tempus. Aliquam vitae dolor aliquam, elementum augue non, molestie nisi. Maecenas aliquet sagittis elit, id elementum magna dictum sed. Vivamus nulla nulla, aliquet et magna ut, tempus ultrices diam. Donec posuere fringilla feugiat. Etiam imperdiet neque nec mollis ornare. Fusce mollis neque risus, ac molestie ligula sagittis vel. Nam tempus et ante eget egestas. Curabitur porta placerat nisi ut vehicula. Nunc suscipit lacinia leo nec tincidunt. Phasellus blandit arcu non pulvinar mollis.\n";

/// Length of `zeros.bin` inside all encrypted fixtures: 2048 zero bytes.
pub const FIXTURE_ZEROS_BIN_LEN: usize = 2048;

/// Byte length of `test.png` inside all encrypted fixtures.
///
/// The PNG content is not inlined (too large for a byte literal). Tasks 3–5
/// that read `test.png` should assert `buf.len() == FIXTURE_TEST_PNG_LEN`.
pub const FIXTURE_TEST_PNG_LEN: usize = 10257;
