//! Cross-parser validation against fixtures generated by trumank/repak.
//!
//! These tests answer "does paksmith agree with an independent UE pak
//! implementation?" using two intentionally-redundant layers:
//!
//! 1. **paksmith-only reads** (`paksmith_reads_repak_*`): paksmith opens
//!    each repak-written fixture and asserts specific entry paths, sizes,
//!    and payload contents. Catches "paksmith can't open this file at
//!    all" with a precise failure message naming the missing entry.
//! 2. **paksmith ↔ repak agreement** (`cross_parser_agreement_*`):
//!    paksmith and repak both read the same fixture and must produce
//!    byte-identical output. Catches subtle disagreements (path
//!    normalization, mount-point handling, byte-offset arithmetic,
//!    header-trailer width) that hardcoded Layer 1 assertions wouldn't
//!    flag — neither parser is privileged as ground truth.
//!
//! Both layers exist on purpose: Layer 1 fails loudly with "expected X
//! got Y" if the fixture itself drifts; Layer 2 fails loudly if either
//! parser drifts from the other. Removing Layer 1 would mean a fixture
//! regenerated by a buggy repak update would pass cross-agreement (both
//! parsers reading the same bug) without anyone noticing.
//!
//! Closes part of #14.

#![allow(missing_docs)]

use std::collections::BTreeMap;
use std::fs::File;
use std::path::PathBuf;

use paksmith_core::container::ContainerReader;
use paksmith_core::container::pak::PakReader;
use paksmith_core::container::pak::version::PakVersion;

fn fixture_path(name: &str) -> PathBuf {
    let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("../../tests/fixtures").join(name)
}

/// Open with repak and return (path → bytes) for every entry. Used as the
/// independent oracle in cross-validation tests.
fn read_with_repak(name: &str) -> BTreeMap<String, Vec<u8>> {
    let path = fixture_path(name);
    let mut file = File::open(&path).unwrap_or_else(|e| panic!("opening fixture `{name}`: {e}"));
    let reader = repak::PakBuilder::new()
        .reader(&mut file)
        .unwrap_or_else(|e| panic!("repak open of `{name}`: {e}"));
    let mut out = BTreeMap::new();
    for entry_path in reader.files() {
        let bytes = reader
            .get(&entry_path, &mut file)
            .unwrap_or_else(|e| panic!("repak get `{entry_path}` from `{name}`: {e}"));
        let _ = out.insert(entry_path, bytes);
    }
    out
}

/// Same shape as [`read_with_repak`] but via paksmith. Symmetric output
/// makes equality assertions trivial.
fn read_with_paksmith(name: &str) -> BTreeMap<String, Vec<u8>> {
    let reader = PakReader::open(fixture_path(name))
        .unwrap_or_else(|e| panic!("paksmith open of `{name}`: {e}"));
    let mut out = BTreeMap::new();
    for meta in reader.list_entries() {
        let bytes = reader
            .read_entry(&meta.path)
            .unwrap_or_else(|e| panic!("paksmith read_entry `{}` from `{name}`: {e}", meta.path));
        let _ = out.insert(meta.path.clone(), bytes);
    }
    out
}

/// Assert paksmith and repak agree on every entry's path and bytes.
fn assert_cross_parser_agreement(name: &str) {
    let paksmith = read_with_paksmith(name);
    let repak = read_with_repak(name);
    assert_eq!(
        paksmith.keys().collect::<Vec<_>>(),
        repak.keys().collect::<Vec<_>>(),
        "{name}: entry paths disagree"
    );
    for (path, paksmith_bytes) in &paksmith {
        let repak_bytes = &repak[path];
        assert_eq!(
            paksmith_bytes, repak_bytes,
            "{name}: byte mismatch for entry `{path}`"
        );
    }
}

// ---------- Layer 1: paksmith reads each fixture standalone -------------

#[test]
fn paksmith_reads_repak_v3_minimal() {
    let reader = PakReader::open(fixture_path("real_v3_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::CompressionEncryption);
    assert_eq!(reader.mount_point(), "../../../");
    let entries = reader.list_entries();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path, "Content/Example.uasset");
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v6_minimal() {
    let reader = PakReader::open(fixture_path("real_v6_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::DeleteRecords);
    assert_eq!(reader.mount_point(), "../../../");
    let entries = reader.list_entries();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path, "Content/Example.uasset");
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v7_minimal() {
    let reader = PakReader::open(fixture_path("real_v7_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::EncryptionKeyGuid);
    assert_eq!(reader.mount_point(), "../../../");
    let entries = reader.list_entries();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path, "Content/Example.uasset");
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v3_multi() {
    let reader = PakReader::open(fixture_path("real_v3_multi.pak")).unwrap();
    let paths: Vec<&str> = reader
        .list_entries()
        .iter()
        .map(|e| e.path.as_str())
        .collect();
    assert_eq!(paths.len(), 3);
    assert!(paths.contains(&"Content/Textures/icon.uasset"));
    assert!(paths.contains(&"Content/Maps/level.umap"));
    assert!(paths.contains(&"Content/Sounds/click.uasset"));
}

#[test]
fn paksmith_reads_repak_v3_mixed_paths() {
    let reader = PakReader::open(fixture_path("real_v3_mixed_paths.pak")).unwrap();
    // Entries at varying directory depths exercise the FString path
    // handling at multiple lengths.
    assert_eq!(reader.read_entry("root.txt").unwrap(), b"depth-zero file");
    assert_eq!(
        reader.read_entry("Content/a.uasset").unwrap(),
        b"depth-one file"
    );
    assert_eq!(
        reader
            .read_entry("Content/Subdir/Deep/nested.uasset")
            .unwrap(),
        b"depth-three file"
    );
}

// ---------- Layer 2: paksmith and repak agree byte-for-byte -------------

#[test]
fn cross_parser_agreement_v3_minimal() {
    assert_cross_parser_agreement("real_v3_minimal.pak");
}

#[test]
fn cross_parser_agreement_v3_multi() {
    assert_cross_parser_agreement("real_v3_multi.pak");
}

#[test]
fn cross_parser_agreement_v3_mixed_paths() {
    assert_cross_parser_agreement("real_v3_mixed_paths.pak");
}

#[test]
fn cross_parser_agreement_v6_minimal() {
    assert_cross_parser_agreement("real_v6_minimal.pak");
}

#[test]
fn cross_parser_agreement_v6_multi() {
    assert_cross_parser_agreement("real_v6_multi.pak");
}

#[test]
fn cross_parser_agreement_v6_mixed_paths() {
    assert_cross_parser_agreement("real_v6_mixed_paths.pak");
}

#[test]
fn cross_parser_agreement_v7_minimal() {
    assert_cross_parser_agreement("real_v7_minimal.pak");
}

#[test]
fn cross_parser_agreement_v7_multi() {
    assert_cross_parser_agreement("real_v7_multi.pak");
}

#[test]
fn cross_parser_agreement_v7_mixed_paths() {
    assert_cross_parser_agreement("real_v7_mixed_paths.pak");
}
