//! Cross-parser validation against fixtures generated by trumank/repak.
//!
//! Lives in the `paksmith-fixture-gen` crate (excluded from the
//! workspace's default-members) so the `repak` git dependency is only
//! resolved when this crate is explicitly built. Run via
//! `cargo test --workspace` (CI) or
//! `cargo test -p paksmith-fixture-gen` (local).
//!
//! These tests answer "does paksmith agree with an independent UE pak
//! implementation?" using two intentionally-redundant layers:
//!
//! 1. **paksmith-only reads** (`paksmith_reads_repak_*`): paksmith opens
//!    each repak-written fixture and asserts specific entry paths, sizes,
//!    and payload contents. Catches "paksmith can't open this file at
//!    all" with a precise failure message naming the missing entry.
//! 2. **paksmith ↔ repak agreement** (`cross_parser_agreement_*`):
//!    paksmith and repak both read the same fixture and must produce
//!    byte-identical output. Catches subtle disagreements (path
//!    normalization, mount-point handling, byte-offset arithmetic,
//!    header-trailer width) that hardcoded Layer 1 assertions wouldn't
//!    flag — neither parser is privileged as ground truth.
//!
//! Both layers exist on purpose: Layer 1 fails loudly with "expected X
//! got Y" if the fixture itself drifts; Layer 2 fails loudly if either
//! parser drifts from the other. Removing Layer 1 would mean a fixture
//! regenerated by a buggy repak update would pass cross-agreement (both
//! parsers reading the same bug) without anyone noticing.
//!
//! A third layer — the SHA1 byte anchor on `real_v3_minimal.pak` —
//! lives in `crates/paksmith-core/tests/fixture_anchor.rs` so it runs
//! in default `cargo test` without pulling repak.
//!
//! Closes part of #14.

#![allow(missing_docs)]

use std::collections::{BTreeMap, BTreeSet};
use std::fs::File;
use std::path::PathBuf;

use paksmith_core::container::ContainerReader;
use paksmith_core::container::pak::PakReader;
use paksmith_core::container::pak::version::PakVersion;

fn fixture_path(name: &str) -> PathBuf {
    let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("../../tests/fixtures").join(name)
}

/// Open with repak and return (path → bytes) for every entry. Used as the
/// independent oracle in cross-validation tests.
fn read_with_repak(name: &str) -> BTreeMap<String, Vec<u8>> {
    let path = fixture_path(name);
    let mut file = File::open(&path).unwrap_or_else(|e| panic!("opening fixture `{name}`: {e}"));
    let reader = repak::PakBuilder::new()
        .reader(&mut file)
        .unwrap_or_else(|e| panic!("repak open of `{name}`: {e}"));
    let mut out = BTreeMap::new();
    for entry_path in reader.files() {
        let bytes = reader
            .get(&entry_path, &mut file)
            .unwrap_or_else(|e| panic!("repak get `{entry_path}` from `{name}`: {e}"));
        let _ = out.insert(entry_path, bytes);
    }
    out
}

/// Same shape as [`read_with_repak`] but via paksmith. Symmetric output
/// makes equality assertions trivial.
fn read_with_paksmith(name: &str) -> BTreeMap<String, Vec<u8>> {
    let reader = PakReader::open(fixture_path(name))
        .unwrap_or_else(|e| panic!("paksmith open of `{name}`: {e}"));
    let mut out = BTreeMap::new();
    for meta in reader.entries() {
        let bytes = reader
            .read_entry(&meta.path)
            .unwrap_or_else(|e| panic!("paksmith read_entry `{}` from `{name}`: {e}", meta.path));
        let _ = out.insert(meta.path, bytes);
    }
    out
}

/// Assert paksmith and repak agree on every entry's path and bytes. On
/// path-set disagreement the failure message names which paths are in
/// one parser's output but not the other's — actionable instead of
/// dumping two parallel `Vec<&String>` for the human to diff manually.
fn assert_cross_parser_agreement(name: &str) {
    let paksmith = read_with_paksmith(name);
    let repak = read_with_repak(name);
    let p_keys: BTreeSet<&String> = paksmith.keys().collect();
    let r_keys: BTreeSet<&String> = repak.keys().collect();
    let only_paksmith: Vec<&&String> = p_keys.difference(&r_keys).collect();
    let only_repak: Vec<&&String> = r_keys.difference(&p_keys).collect();
    assert!(
        only_paksmith.is_empty() && only_repak.is_empty(),
        "{name}: entry paths disagree\n  only in paksmith: {only_paksmith:?}\n  only in repak:    {only_repak:?}"
    );
    for (path, paksmith_bytes) in &paksmith {
        let repak_bytes = &repak[path];
        assert_eq!(
            paksmith_bytes, repak_bytes,
            "{name}: byte mismatch for entry `{path}`"
        );
    }
}

// ---------- Layer 1: paksmith reads each fixture standalone -------------

#[test]
fn paksmith_reads_repak_v3_minimal() {
    let reader = PakReader::open(fixture_path("real_v3_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::CompressionEncryption);
    assert_eq!(reader.mount_point(), "../../../");
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path, "Content/Example.uasset");
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v6_minimal() {
    let reader = PakReader::open(fixture_path("real_v6_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::DeleteRecords);
    assert_eq!(reader.mount_point(), "../../../");
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path, "Content/Example.uasset");
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v7_minimal() {
    let reader = PakReader::open(fixture_path("real_v7_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::EncryptionKeyGuid);
    assert_eq!(reader.mount_point(), "../../../");
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path, "Content/Example.uasset");
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v3_multi() {
    let reader = PakReader::open(fixture_path("real_v3_multi.pak")).unwrap();
    let paths: Vec<String> = reader.entries().map(|e| e.path).collect();
    assert_eq!(paths.len(), 3);
    assert!(paths.iter().any(|p| p == "Content/Textures/icon.uasset"));
    assert!(paths.iter().any(|p| p == "Content/Maps/level.umap"));
    assert!(paths.iter().any(|p| p == "Content/Sounds/click.uasset"));
}

#[test]
fn paksmith_reads_repak_v3_mixed_paths() {
    let reader = PakReader::open(fixture_path("real_v3_mixed_paths.pak")).unwrap();
    // Entries at varying directory depths exercise the FString path
    // handling at multiple lengths.
    assert_eq!(reader.read_entry("root.txt").unwrap(), b"depth-zero file");
    assert_eq!(
        reader.read_entry("Content/a.uasset").unwrap(),
        b"depth-one file"
    );
    assert_eq!(
        reader
            .read_entry("Content/Subdir/Deep/nested.uasset")
            .unwrap(),
        b"depth-three file"
    );
}

// ---------- Layer 2: paksmith and repak agree byte-for-byte -------------

#[test]
fn cross_parser_agreement_v3_minimal() {
    assert_cross_parser_agreement("real_v3_minimal.pak");
}

#[test]
fn cross_parser_agreement_v3_multi() {
    assert_cross_parser_agreement("real_v3_multi.pak");
}

#[test]
fn cross_parser_agreement_v3_mixed_paths() {
    assert_cross_parser_agreement("real_v3_mixed_paths.pak");
}

#[test]
fn cross_parser_agreement_v6_minimal() {
    assert_cross_parser_agreement("real_v6_minimal.pak");
}

#[test]
fn cross_parser_agreement_v6_multi() {
    assert_cross_parser_agreement("real_v6_multi.pak");
}

#[test]
fn cross_parser_agreement_v6_mixed_paths() {
    assert_cross_parser_agreement("real_v6_mixed_paths.pak");
}

#[test]
fn cross_parser_agreement_v7_minimal() {
    assert_cross_parser_agreement("real_v7_minimal.pak");
}

#[test]
fn cross_parser_agreement_v7_multi() {
    assert_cross_parser_agreement("real_v7_multi.pak");
}

#[test]
fn cross_parser_agreement_v7_mixed_paths() {
    assert_cross_parser_agreement("real_v7_mixed_paths.pak");
}

// V8A: 4-slot FName compression-method table; per-entry compression
// byte is u8 (3 bytes shorter than V8B+).
#[test]
fn paksmith_reads_repak_v8a_minimal() {
    let reader = PakReader::open(fixture_path("real_v8a_minimal.pak")).unwrap();
    // Footer parser post-corrects V8B (the TryFrom default for
    // wire-version 8) to V8A based on the 4-slot FName table.
    assert_eq!(reader.version(), PakVersion::V8A);
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v8a_multi() {
    let reader = PakReader::open(fixture_path("real_v8a_multi.pak")).unwrap();
    let paths: Vec<String> = reader.entries().map(|e| e.path).collect();
    assert_eq!(paths.len(), 3);
    assert!(paths.iter().any(|p| p == "Content/Textures/icon.uasset"));
    assert!(paths.iter().any(|p| p == "Content/Maps/level.umap"));
    assert!(paths.iter().any(|p| p == "Content/Sounds/click.uasset"));
}

#[test]
fn cross_parser_agreement_v8a_minimal() {
    assert_cross_parser_agreement("real_v8a_minimal.pak");
}

#[test]
fn cross_parser_agreement_v8a_multi() {
    assert_cross_parser_agreement("real_v8a_multi.pak");
}

#[test]
fn cross_parser_agreement_v8a_mixed_paths() {
    assert_cross_parser_agreement("real_v8a_mixed_paths.pak");
}

// V8B: 5-slot FName compression-method table; per-entry compression
// byte is back to u32 (same wire shape as v3-v7 entries).
#[test]
fn paksmith_reads_repak_v8b_minimal() {
    let reader = PakReader::open(fixture_path("real_v8b_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::V8B);
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v8b_multi() {
    let reader = PakReader::open(fixture_path("real_v8b_multi.pak")).unwrap();
    let paths: Vec<String> = reader.entries().map(|e| e.path).collect();
    assert_eq!(paths.len(), 3);
    assert!(paths.iter().any(|p| p == "Content/Textures/icon.uasset"));
    assert!(paths.iter().any(|p| p == "Content/Maps/level.umap"));
    assert!(paths.iter().any(|p| p == "Content/Sounds/click.uasset"));
}

#[test]
fn cross_parser_agreement_v8b_minimal() {
    assert_cross_parser_agreement("real_v8b_minimal.pak");
}

#[test]
fn cross_parser_agreement_v8b_multi() {
    assert_cross_parser_agreement("real_v8b_multi.pak");
}

#[test]
fn cross_parser_agreement_v8b_mixed_paths() {
    assert_cross_parser_agreement("real_v8b_mixed_paths.pak");
}

// V9: V8B layout + 1 frozen-index byte in the footer.
#[test]
fn paksmith_reads_repak_v9_minimal() {
    let reader = PakReader::open(fixture_path("real_v9_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::FrozenIndex);
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v9_multi() {
    let reader = PakReader::open(fixture_path("real_v9_multi.pak")).unwrap();
    let paths: Vec<String> = reader.entries().map(|e| e.path).collect();
    assert_eq!(paths.len(), 3);
    assert!(paths.iter().any(|p| p == "Content/Textures/icon.uasset"));
    assert!(paths.iter().any(|p| p == "Content/Maps/level.umap"));
    assert!(paths.iter().any(|p| p == "Content/Sounds/click.uasset"));
}

#[test]
fn cross_parser_agreement_v9_minimal() {
    assert_cross_parser_agreement("real_v9_minimal.pak");
}

#[test]
fn cross_parser_agreement_v9_multi() {
    assert_cross_parser_agreement("real_v9_multi.pak");
}

#[test]
fn cross_parser_agreement_v9_mixed_paths() {
    assert_cross_parser_agreement("real_v9_mixed_paths.pak");
}

// V10: PathHashIndex format (mount + count + seed + path-hash table +
// full directory index + bit-packed encoded entries). Wholly different
// index layout from v3-v9; goes through `PakIndex::read_v10_plus_from`.
#[test]
fn paksmith_reads_repak_v10_minimal() {
    let reader = PakReader::open(fixture_path("real_v10_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::PathHashIndex);
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v10_multi() {
    let reader = PakReader::open(fixture_path("real_v10_multi.pak")).unwrap();
    let paths: Vec<String> = reader.entries().map(|e| e.path).collect();
    assert_eq!(paths.len(), 3);
    assert!(paths.iter().any(|p| p == "Content/Textures/icon.uasset"));
    assert!(paths.iter().any(|p| p == "Content/Maps/level.umap"));
    assert!(paths.iter().any(|p| p == "Content/Sounds/click.uasset"));
}

#[test]
fn cross_parser_agreement_v10_minimal() {
    assert_cross_parser_agreement("real_v10_minimal.pak");
}

#[test]
fn cross_parser_agreement_v10_multi() {
    assert_cross_parser_agreement("real_v10_multi.pak");
}

#[test]
fn cross_parser_agreement_v10_mixed_paths() {
    assert_cross_parser_agreement("real_v10_mixed_paths.pak");
}

// V11: same shape as V10, with the FNV-64 path-hash bug fixed. For
// ASCII paths the two are byte-identical, so this exercises the same
// code path as v10 — but version-classification differs.
#[test]
fn paksmith_reads_repak_v11_minimal() {
    let reader = PakReader::open(fixture_path("real_v11_minimal.pak")).unwrap();
    assert_eq!(reader.version(), PakVersion::Fnv64BugFix);
    let entries: Vec<_> = reader.entries().collect();
    assert_eq!(entries.len(), 1);
    let data = reader.read_entry("Content/Example.uasset").unwrap();
    assert_eq!(data, b"EXAMPLE_PAYLOAD_BYTES");
}

#[test]
fn paksmith_reads_repak_v11_multi() {
    let reader = PakReader::open(fixture_path("real_v11_multi.pak")).unwrap();
    let paths: Vec<String> = reader.entries().map(|e| e.path).collect();
    assert_eq!(paths.len(), 3);
    assert!(paths.iter().any(|p| p == "Content/Textures/icon.uasset"));
    assert!(paths.iter().any(|p| p == "Content/Maps/level.umap"));
    assert!(paths.iter().any(|p| p == "Content/Sounds/click.uasset"));
}

#[test]
fn cross_parser_agreement_v11_minimal() {
    assert_cross_parser_agreement("real_v11_minimal.pak");
}

#[test]
fn cross_parser_agreement_v11_multi() {
    assert_cross_parser_agreement("real_v11_multi.pak");
}

#[test]
fn cross_parser_agreement_v11_mixed_paths() {
    assert_cross_parser_agreement("real_v11_mixed_paths.pak");
}
