name: Security Audit

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  audit:
    name: cargo-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
